# Generated by Django 5.2.17 on 2026-09-27 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='Absolute English Spoken & Pronunciation Masterclass', max_length=200)),
                ('batch_name', models.CharField(default='Morning Batch A (Mon-Fri, 10:00 AM - 11:30 AM)', max_length=200)),
                ('trainer_name', models.CharField(default='Prof. David Miller (Senior Native Trainer)', max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active Student'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('progress_percent', models.IntegerField(default=45)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
            },
        ),
        migrations.CreateModel(
            name='LiveClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='Real-Life Conversation Practice & Accent Training', max_length=250)),
                ('instructor', models.CharField(default='Prof. Sarah Jenkins', max_length=150)),
                ('scheduled_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting_link', models.URLField(default='https://zoom.us/j/123456789')),
                ('is_live', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Class Session',
                'verbose_name_plural': 'Live Class Sessions',
            },
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='IELTS & Spoken English Listening/Speaking Assessment #1', max_length=200)),
                ('total_questions', models.IntegerField(default=25)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('pending', 'Pending / Available'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('total_marks', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Test',
                'verbose_name_plural': 'Student Tests',
            },
        ),
    ]
