# Generated by Django 6.0.3 on 2026-09-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('language', models.CharField(choices=[('American English', 'American English'), ('British English', 'British English')], max_length=50)),
                ('level', models.CharField(choices=[('A1 - Beginner', 'A1 - Beginner'), ('A2 - Elementary', 'A2 - Elementary'), ('B1 - Intermediate', 'B1 - Intermediate'), ('B2 - Upper Intermediate', 'B2 - Upper Intermediate'), ('C1 - Advanced', 'C1 - Advanced')], max_length=50)),
                ('address', models.TextField()),
                ('agree_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
